### ISSUE TITLE
Салам молекулам

### ISSUE THREAD

**Issue by kan5** [IlyaGusev/rupo#14]
У меня windows 10. Скачал я значит docker, взял ubuntu.

- apt update(всё без sudo)
- apt install git
- apt install python3-pip
- apt install wget
- apt install unzip
- git clone https://github.com/IlyaGusev/rupo
- cd rupo
- поменял в requirements '>=' на '==' через vim
- pip3 install -r requirements.txt
- sh download.sh
- python3 generate_poem.py

`Traceback (most recent call last):
  File "generate_poem.py", line 3, in <module>
    from rupo.api import Engine
  File "/rupo/rupo/api.py", line 8, in <module>
    from rulm.language_model import LanguageModel
ModuleNotFoundError: No module named 'rulm'`

- попробовал pip3 install rulm, не прокатило

**Comment by IlyaGusev** [comment]
Пример запуска: https://colab.research.google.com/drive/1WBl9erJvC9Oc9PjCD8JyC_40TDUqahCx

Вероятно что-то не так с именованием папок
